# Generated by Django 3.0.7 on 2020-07-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='film_star',
            new_name='characters',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='film_star',
            new_name='characters',
        ),
        migrations.AddField(
            model_name='film',
            name='story_line',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
